# Generated by Django 4.2.4 on 2023-09-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='image',
            field=models.ImageField(default='default_actors.jpeg', upload_to='pictures'),
        ),
    ]
